package box

import (
	"context"
	"encoding/csv"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"syscall"

	agents "github.com/AndrewDryga/coop/internal/agent"
	"github.com/AndrewDryga/coop/internal/config"
	"github.com/AndrewDryga/coop/internal/forkspace"
	"github.com/AndrewDryga/coop/internal/networkstate"
	"github.com/AndrewDryga/coop/internal/runtime"
)

type authorityBind struct {
	source   string
	writable bool
}

type authorityMountPlan struct {
	binds                            []authorityBind
	writableVolumes, readonlyVolumes []string
	envFiles                         []string
	volumesFrom, customVolumeDriver  bool
}

type volumeExposureReader func(context.Context, []string) (runtime.VolumeExposure, error)

type authorityMountAllowlist struct {
	sources         map[string]bool // exact, descriptor-validated generated sources
	readonlySources map[string]bool // exact host-selected sources that must stay read-only
	envFiles        map[string]bool // exact scoped environment files selected/generated by Coop
	sourceTrees     []string        // generated directories whose mounted descendants are also owned
	volumes         map[string]bool // run-private volumes whose creator owns their contents
	privateRoots    []string        // per-run host state; exact generated children may be allowlisted
}

// protectRunPrivateState keeps operator-supplied runtime binds from widening a run's credential
// scope or exposing Coop's host control plane. Only sources the ordinary assembly already chose
// are exact-allowed: selected provider profiles, the requested ACP transcript store, generated
// files, and one remote-session output subtree.
func protectRunPrivateState(cfg *config.Config, spec RunSpec, allow authorityMountAllowlist) (authorityMountAllowlist, error) {
	if allow.sources == nil {
		allow.sources = map[string]bool{}
	}
	if cfg != nil {
		for _, root := range ConfigExposureRoots(cfg) {
			allow.privateRoots = appendUniqueAuthorityPath(allow.privateRoots, root)
		}
		if cfg.MCPFile != "" {
			allow.privateRoots = appendUniqueAuthorityPath(allow.privateRoots, cfg.MCPFile)
		}
		for _, name := range credentialScope(cfg, spec) {
			allow.sources[cfg.AgentDir(name)] = true
		}
		if spec.ShareACPSessions {
			if primary := runPrimary(spec); primary != "" {
				if agent, ok := agents.Get(primary); ok {
					for _, name := range agent.ACPSessionDirs() {
						allow.sources[filepath.Join(acpSharedDir(cfg, primary), name)] = true
					}
				}
			}
		}
		if stateRoot := remoteSessionStateRoot(cfg, spec); stateRoot != "" {
			allow.privateRoots = appendUniqueAuthorityPath(allow.privateRoots, stateRoot)
			if err := allowControllerJobSources(cfg, spec, stateRoot, &allow); err != nil {
				return allow, err
			}
			if spec.SessionOutputRoot != "" && filepath.Clean(filepath.Dir(spec.SessionOutputRoot)) != filepath.Join(stateRoot, "output") {
				return allow, errors.New("read-only session output is outside its private session state")
			}
		} else if spec.SessionOutputRoot != "" {
			return allow, errors.New("read-only session output has no private session state")
		}
	}
	if spec.SessionOutputRoot != "" {
		allow.sources[spec.SessionOutputRoot] = true
	}
	return allow, nil
}

// A controller job's fetched source and companion snapshots live inside the service's otherwise
// protected state. Admit only this run's bound, owner-private mount roots; the rest of that tree
// (including the source mirror, other sessions and control socket) stays behind the fence.
func allowControllerJobSources(cfg *config.Config, spec RunSpec, stateRoot string, allow *authorityMountAllowlist) error {
	if !spec.ControllerJob || spec.RunID == "" || spec.ForkName == "" || spec.ForkGeneration == "" {
		return nil
	}
	sessionID := filepath.Base(cfg.ConfigDir)
	if spec.ActivityKind != "" && spec.ActivityKind != forkspace.ExecutionRemoteSession ||
		spec.ActivityReservationOwner != "" && spec.ActivityReservationOwner != sessionID {
		return nil
	}
	sourceRepo, identity, err := forkspace.ResolveProjectBinding(spec.Repo)
	if err != nil {
		return err
	}
	if identity == nil || identity.Name != spec.ForkName || string(identity.Generation) != spec.ForkGeneration ||
		spec.ActivityRepo != "" && spec.ActivityRepo != sourceRepo {
		return nil
	}
	reservation, reserved, err := forkspace.ReadWorkspaceReservation(sourceRepo, *identity)
	if err != nil {
		return err
	}
	if !reserved || reservation.Kind != forkspace.WorkspaceReservationRemoteSession || reservation.OwnerID != sessionID {
		return nil
	}
	// The service may have staged the primary under a state-root alias (for example macOS
	// /var -> /private/var); the credential projection uses the canonical root. Permit that
	// ancestor alias, but never a symlink inside the service-owned source tree.
	sourceStateRoot := filepath.Dir(filepath.Dir(filepath.Dir(sourceRepo)))
	canonicalRoot, err := filepath.EvalSymlinks(sourceStateRoot)
	if err != nil {
		return err
	}
	configuredRoot, err := filepath.EvalSymlinks(stateRoot)
	if err != nil {
		return err
	}
	if canonicalRoot != configuredRoot {
		return nil
	}
	rel, err := filepath.Rel(filepath.Join(sourceStateRoot, "job-sources"), sourceRepo)
	if err != nil {
		return err
	}
	parts := strings.Split(rel, string(filepath.Separator))
	if len(parts) != 2 || len(parts[0]) != 64 || parts[1] != "repository" ||
		!lowerHex(parts[0]) || spec.Repo != forkspace.Workspace(sourceRepo, spec.ForkName) {
		return nil
	}
	if err := validateGeneratedSessionSource(sourceStateRoot, spec.Repo); err != nil {
		return err
	}
	allow.sources[spec.Repo] = true
	for _, companion := range spec.CompanionRepositories {
		if companion.Name == "" || filepath.Base(companion.Name) != companion.Name ||
			companion.Name == "." || companion.Name == ".." ||
			companion.HostPath != filepath.Join(stateRoot, "repositories", sessionID, companion.Name) {
			return errors.New("controller job companion mount is outside its session")
		}
		if err := validateGeneratedSessionSource(stateRoot, companion.HostPath); err != nil {
			return err
		}
		if allow.readonlySources == nil {
			allow.readonlySources = map[string]bool{}
		}
		allow.readonlySources[companion.HostPath] = true
	}
	return nil
}

func validateGeneratedSessionSource(root, source string) error {
	rel, err := filepath.Rel(root, source)
	if err != nil || rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return errors.New("controller job mount is outside session state")
	}
	parts := strings.Split(rel, string(filepath.Separator))
	path := root
	for index := -1; index < len(parts); index++ {
		if index >= 0 {
			path = filepath.Join(path, parts[index])
		}
		info, err := os.Lstat(path)
		if err != nil {
			return fmt.Errorf("inspect controller job mount %q: %w", path, err)
		}
		stat, owned := info.Sys().(*syscall.Stat_t)
		// The service state, source store and per-session directory are private. Fork homes
		// and Git checkouts may be 0755, but their private ancestor keeps them unreachable.
		if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 || !owned || stat.Uid != uint32(os.Geteuid()) ||
			index < 2 && info.Mode().Perm()&0o077 != 0 {
			return fmt.Errorf("controller job mount %q has an unsafe directory", path)
		}
	}
	return nil
}

func lowerHex(value string) bool {
	for _, digit := range value {
		if digit < '0' || digit > '9' && digit < 'a' || digit > 'f' {
			return false
		}
	}
	return true
}

func remoteSessionStateRoot(cfg *config.Config, spec RunSpec) string {
	if cfg == nil || cfg.ConfigDir == "" || spec.RunID == "" {
		return ""
	}
	acpRoot := filepath.Dir(filepath.Clean(cfg.ConfigDir))
	if filepath.Base(acpRoot) != "acp" {
		return ""
	}
	return filepath.Dir(acpRoot)
}

func appendUniqueAuthorityPath(paths []string, path string) []string {
	if path != "" && !slices.Contains(paths, path) {
		return append(paths, path)
	}
	return paths
}

// enterAuthorityMountWindow makes validation and the following runtime lifetime one shared
// interval. A first project anchor takes the matching exclusive lock, so a launch validated before
// that transition cannot start afterwards with mount authority the anchored policy would refuse.
func enterAuthorityMountWindow(ctx context.Context, repo string, validate func() error) (func(), error) {
	unlock, err := forkspace.LockServiceLaunch(ctx, repo, false)
	if err != nil {
		return nil, fmt.Errorf("enter the sandbox mount window: %w", err)
	}
	if err := validate(); err != nil {
		unlock()
		return nil, err
	}
	return unlock, nil
}

// validateAuthorityMounts closes the one extra capability a hardlink anchor introduces: a box
// may mount the anchored root itself, but not an agent-controlled path below it, a writable ancestor
// from which it could rename the root, or any view of Coop's private half of the link.
func validateAuthorityMounts(ctx context.Context, spec RunSpec, options []string, networkState string, volumes volumeExposureReader, allow authorityMountAllowlist) error {
	evalRoot, err := evalAuthorityRoot()
	if err != nil {
		return err
	}
	allow.privateRoots = appendUniqueAuthorityPath(allow.privateRoots, evalRoot)
	if err := allowEvalMountSources(spec, evalRoot, &allow); err != nil {
		return err
	}
	projects, private, err := authorityProtection(spec, networkState)
	if err != nil {
		return err
	}
	private = append(private, allow.privateRoots...)
	if len(projects) == 0 && len(private) == 0 {
		return nil
	}
	plan, err := parseAuthorityMountPlan(options)
	if err != nil {
		return err
	}
	allowedEnvFiles := map[string]string{}
	for source := range allow.envFiles {
		canonical, err := resolveAuthorityPath(source)
		if err != nil {
			return fmt.Errorf("inspect scoped runtime environment file %q: %w", source, err)
		}
		allowedEnvFiles[source] = canonical
	}
	for _, source := range plan.envFiles {
		expected, allowed := allowedEnvFiles[source]
		if !allowed {
			return fmt.Errorf("runtime environment file %q is not the scoped environment Coop prepared; put ordinary variables in Coop's env file or pass explicit -e KEY=VALUE entries", source)
		}
		canonical, err := resolveAuthorityPath(source)
		if err != nil {
			return fmt.Errorf("inspect runtime environment file %q: %w", source, err)
		}
		if canonical != expected {
			return fmt.Errorf("runtime environment file %q changed after Coop prepared it", source)
		}
	}
	if plan.volumesFrom {
		return errors.New("an anchored box cannot use --volumes-from because its host sources cannot be proven private")
	}
	if plan.customVolumeDriver {
		return errors.New("an anchored box cannot create a runtime volume with custom driver options; use an existing inspected volume or an explicit bind")
	}
	allowedSources := map[string]bool{}
	for source := range allow.sources {
		canonical, err := resolveAuthorityPath(source)
		if err != nil {
			return err
		}
		allowedSources[canonical] = true
	}
	readonlySources := map[string]bool{}
	for source := range allow.readonlySources {
		canonical, err := resolveAuthorityPath(source)
		if err != nil {
			return err
		}
		allowedSources[canonical] = true
		readonlySources[canonical] = true
	}
	var allowedSourceTrees []string
	for _, source := range allow.sourceTrees {
		canonical, err := resolveAuthorityPath(source)
		if err != nil {
			return err
		}
		allowedSourceTrees = append(allowedSourceTrees, canonical)
	}
	sources := append([]authorityBind(nil), plan.binds...)
	for _, bind := range sources {
		canonical, err := resolveAuthorityPath(bind.source)
		if err != nil {
			return err
		}
		if bind.writable && readonlySources[canonical] {
			return fmt.Errorf("runtime mount %q must be read-only", bind.source)
		}
		if err := checkAuthoritySource(bind.source, bind.writable, projects, private, allowedSources, allowedSourceTrees); err != nil {
			return err
		}
	}
	if len(plan.writableVolumes)+len(plan.readonlyVolumes) == 0 {
		return checkMutableMountSources(sources)
	}
	if volumes == nil {
		return errors.New("anchored runtime volumes require an inspectable runtime")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	writableVolumes := slices.DeleteFunc(append([]string(nil), plan.writableVolumes...), func(name string) bool { return allow.volumes[name] })
	readonlyVolumes := slices.DeleteFunc(append([]string(nil), plan.readonlyVolumes...), func(name string) bool {
		return allow.volumes[name] || slices.Contains(writableVolumes, name)
	})
	for _, group := range []struct {
		names    []string
		writable bool
	}{{writableVolumes, true}, {readonlyVolumes, false}} {
		if len(group.names) == 0 {
			continue
		}
		exposure, err := volumes(ctx, group.names)
		if err != nil {
			return fmt.Errorf("inspect anchored runtime volumes: %w", err)
		}
		for _, source := range exposure.Sources {
			if err := checkAuthoritySource(source, group.writable, projects, private, nil, nil); err != nil {
				return err
			}
			sources = append(sources, authorityBind{source: source, writable: group.writable})
		}
	}
	return checkMutableMountSources(sources)
}

func evalAuthorityRoot() (string, error) {
	networkRoot, err := NetworkStatePath()
	if err != nil {
		return "", err
	}
	return filepath.Join(filepath.Dir(networkRoot), "eval"), nil
}

// Only the exact directories Coop generated for this trial cross the private-state fence.
// A loop-suite child has no in-process grant from its parent, so the layout itself is the
// host-side proof; each component below eval is real and owner-private.
func allowEvalMountSources(spec RunSpec, root string, allow *authorityMountAllowlist) error {
	if parts, ok := evalSourceParts(root, spec.Repo); ok && len(parts) == 4 &&
		parts[1] == "work" && ((parts[3] == "workspace" && !spec.GradeSnapshot) ||
		(parts[3] == "snapshot" && spec.GradeSnapshot && !spec.Homes)) {
		if err := validateEvalSource(root, parts, 3); err != nil {
			return err
		}
		if allow.sources == nil {
			allow.sources = map[string]bool{}
		}
		allow.sources[spec.Repo] = true
	}
	if parts, ok := evalSourceParts(root, spec.EvalVerifier); ok && len(parts) == 4 &&
		parts[0] == "starters" && parts[2] == "verifiers" && spec.GradeSnapshot && !spec.Homes {
		if err := validateEvalSource(root, parts, 0); err != nil {
			return err
		}
		if allow.readonlySources == nil {
			allow.readonlySources = map[string]bool{}
		}
		allow.readonlySources[spec.EvalVerifier] = true
	}
	return nil
}

func evalSourceParts(root, source string) ([]string, bool) {
	if source == "" || !filepath.IsAbs(source) {
		return nil, false
	}
	rel, err := filepath.Rel(root, source)
	if err != nil || rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return nil, false
	}
	return strings.Split(rel, string(filepath.Separator)), true
}

func validateEvalSource(root string, parts []string, privateThrough int) error {
	path := root
	for i := -1; i < len(parts); i++ {
		if i >= 0 {
			path = filepath.Join(path, parts[i])
		}
		info, err := os.Lstat(path)
		if err != nil {
			return fmt.Errorf("inspect generated eval mount %q: %w", path, err)
		}
		stat, owned := info.Sys().(*syscall.Stat_t)
		if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 || !owned || stat.Uid != uint32(os.Geteuid()) {
			return fmt.Errorf("generated eval mount %q is not a real owner-owned directory", path)
		}
		if i < privateThrough && info.Mode().Perm()&0o077 != 0 {
			return fmt.Errorf("generated eval mount %q is not owner-private", path)
		}
	}
	return nil
}

func checkMutableMountSources(sources []authorityBind) error {
	for i, root := range sources {
		if !root.writable {
			continue
		}
		for j, source := range sources {
			if i == j {
				continue
			}
			inside, exact, err := authorityContains(root.source, source.source)
			if err != nil {
				return err
			}
			if exact {
				continue
			}
			rawInside, err := aliasesAuthorityAncestor(root.source, filepath.Dir(filepath.Clean(source.source)))
			if err != nil {
				return err
			}
			if inside || rawInside {
				return fmt.Errorf("runtime mount source %q is nested below writable source %q; mount only the parent or move the nested source outside it", source.source, root.source)
			}
		}
	}
	return nil
}

func authorityProtection(spec RunSpec, networkState string) ([]string, []string, error) {
	var projects, private []string
	if networkState != "" {
		// The first approval creates this authority tree. Protect its prospective path too, or a
		// box started on a fresh host could prepopulate the same-UID store through a broad bind.
		private = appendUniqueAuthorityPath(private, networkState)
		// Production network state is <XDG state>/coop/network. Protect its whole
		// Coop sibling tree (evals, sessions, and future authority) without treating
		// an arbitrary test store path as permission to fence its broad temp parent.
		if filepath.Base(networkState) == "network" {
			private = appendUniqueAuthorityPath(private, filepath.Dir(networkState))
		}
	}
	serviceApprovals, err := serviceApprovalRoot()
	if err != nil {
		return nil, nil, fmt.Errorf("locate private Coop service state: %w", err)
	}
	private = appendUniqueAuthorityPath(private, filepath.Dir(serviceApprovals))
	if root := os.Getenv(forkspace.GitViewRootEnv); root != "" {
		private = appendUniqueAuthorityPath(private, root)
	}
	policyRepo := projectPolicyRepo(spec)
	if policyRepo != "" {
		canonical, err := canonicalProjectDir(policyRepo)
		if err != nil {
			return nil, nil, err
		}
		private, err = appendProjectPrivateAuthority(private, canonical)
		if err != nil {
			return nil, nil, err
		}
		_, networkMarkerErr := os.Lstat(filepath.Join(canonical, networkstate.ProjectApprovalMarker))
		_, serviceMarkerErr := os.Lstat(filepath.Join(canonical, serviceApprovalMarker))
		if networkMarkerErr == nil || serviceMarkerErr == nil {
			projects = append(projects, canonical)
		} else if !errors.Is(networkMarkerErr, os.ErrNotExist) {
			return nil, nil, networkMarkerErr
		} else if !errors.Is(serviceMarkerErr, os.ErrNotExist) {
			return nil, nil, serviceMarkerErr
		}
	}
	if spec.ActivityRepo != "" {
		var err error
		private, err = appendProjectPrivateAuthority(private, spec.ActivityRepo)
		if err != nil {
			return nil, nil, err
		}
	}
	// Companion repositories are first-class model-writable roots even though this particular run
	// mounts them read-only: another concurrent Coop box may be writing one. Refuse independently
	// mounted descendants so that writer cannot swap a checked source to a host symlink before the
	// runtime opens it. The exact companion root remains the planned, stable mount boundary.
	for _, companion := range spec.CompanionRepositories {
		canonical, err := canonicalProjectDir(companion.HostPath)
		if err != nil {
			return nil, nil, fmt.Errorf("inspect companion repository %q: %w", companion.Name, err)
		}
		if !slices.Contains(projects, canonical) {
			projects = append(projects, canonical)
		}
		private, err = appendProjectPrivateAuthority(private, canonical)
		if err != nil {
			return nil, nil, err
		}
	}
	if spec.ForkGeneration == "" {
		return projects, private, nil
	}
	identity := forkspace.Identity{Name: spec.ForkName, Generation: forkspace.Generation(spec.ForkGeneration)}
	authorityRepo := spec.ActivityRepo
	if authorityRepo == "" {
		resolved, bound, err := forkspace.ResolveProjectBinding(spec.Repo)
		if err != nil {
			return nil, nil, err
		}
		if bound == nil || *bound != identity {
			return nil, nil, errors.New("fork mount authority does not match this workspace generation")
		}
		authorityRepo = resolved
	} else if err := forkspace.ValidateGenerationWorkspace(authorityRepo, identity); err != nil {
		return nil, nil, err
	}
	workspace, err := filepath.EvalSymlinks(spec.Repo)
	if err != nil {
		return nil, nil, errors.New("fork mount authority workspace cannot be resolved")
	}
	expectedWorkspace, err := filepath.EvalSymlinks(forkspace.Workspace(authorityRepo, identity.Name))
	if err != nil || filepath.Clean(workspace) != filepath.Clean(expectedWorkspace) {
		return nil, nil, errors.New("fork mount authority points at another workspace")
	}
	projects = append(projects, workspace)
	private = appendUniqueAuthorityPath(private, forkspace.StateDir(authorityRepo))
	return projects, private, nil
}

func appendProjectPrivateAuthority(private []string, repo string) ([]string, error) {
	canonical, err := canonicalProjectDir(repo)
	if err != nil {
		return nil, err
	}
	registries, err := forkspace.ExecutionRegistryDirs(canonical)
	if err != nil {
		return nil, fmt.Errorf("locate execution authority state: %w", err)
	}
	// Both are authority before they exist: the first fork creates StateDir, while ordinary boxes
	// create the fallback registry and its service-launch lock on first use.
	for _, path := range append([]string{forkspace.StateDir(canonical)}, registries...) {
		if !slices.Contains(private, path) {
			private = append(private, path)
		}
	}
	serviceLock, err := forkspace.ServiceLaunchLockPath(canonical)
	if err != nil {
		return nil, fmt.Errorf("locate service launch authority: %w", err)
	}
	private = appendUniqueAuthorityPath(private, filepath.Dir(serviceLock))
	return private, nil
}

func checkAuthoritySource(source string, writable bool, projects, private []string, allowed map[string]bool, allowedTrees []string) error {
	canonical, err := resolveAuthorityPath(source)
	if err != nil {
		return fmt.Errorf("inspect runtime mount source %q: %w", source, err)
	}
	for _, state := range private {
		overlap, err := authorityPathsOverlap(canonical, state)
		if err != nil {
			return err
		}
		generated := allowed[canonical] || slices.ContainsFunc(allowedTrees, func(root string) bool { return pathContains(root, canonical) })
		if overlap && !generated {
			return fmt.Errorf("runtime mount %q overlaps Coop's protected host path %q (even read-only mounts are blocked); remove it from COOP_RUN_ARGS or use a source outside Coop's protected state", source, state)
		}
	}
	for _, project := range projects {
		inside, exact, err := authorityContains(project, canonical)
		if err != nil {
			return err
		}
		// Read-only controls the resulting mount, not resolution of its host source. A source name
		// inside a writable project can be swapped to an authority path after this check and before
		// the runtime opens it. Check the raw parent as well as the currently resolved source so a
		// symlink that is safe at validation time gets no race window.
		parentInside, err := aliasesAuthorityAncestor(project, filepath.Dir(filepath.Clean(source)))
		if err != nil {
			return err
		}
		if (inside && !exact) || (parentInside && filepath.Clean(source) != filepath.Clean(project)) {
			return fmt.Errorf("runtime mount %q uses a path inside anchored project %q; mount the exact project or an unrelated host path instead", source, project)
		}
		if !writable {
			continue
		}
		contains, exact, err := authorityContains(canonical, project)
		if err != nil {
			return err
		}
		if contains && !exact {
			return fmt.Errorf("writable runtime mount %q contains anchored project %q; mount the exact project or an unrelated host path instead", source, project)
		}
	}
	return nil
}

func resolveAuthorityPath(path string) (string, error) {
	if !filepath.IsAbs(path) || strings.ContainsAny(path, "\x00\r\n") {
		return "", errors.New("mount source must be an absolute host path")
	}
	probe := filepath.Clean(path)
	var tail []string
	for {
		resolved, err := filepath.EvalSymlinks(probe)
		if err == nil {
			for i := len(tail) - 1; i >= 0; i-- {
				resolved = filepath.Join(resolved, tail[i])
			}
			return filepath.Clean(resolved), nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		parent := filepath.Dir(probe)
		if parent == probe {
			return "", err
		}
		tail = append(tail, filepath.Base(probe))
		probe = parent
	}
}

func authorityPathsOverlap(a, b string) (bool, error) {
	a, err := resolveAuthorityPath(a)
	if err != nil {
		return false, err
	}
	b, err = resolveAuthorityPath(b)
	if err != nil {
		return false, err
	}
	if pathContains(a, b) || pathContains(b, a) {
		return true, nil
	}
	left, err := aliasesAuthorityAncestor(a, b)
	if err != nil || left {
		return left, err
	}
	return aliasesAuthorityAncestor(b, a)
}

func authorityContains(root, path string) (contains, exact bool, err error) {
	root, err = resolveAuthorityPath(root)
	if err != nil {
		return false, false, err
	}
	path, err = resolveAuthorityPath(path)
	if err != nil {
		return false, false, err
	}
	if pathContains(root, path) {
		return true, root == path, nil
	}
	rootInfo, rootErr := os.Stat(root)
	pathInfo, pathErr := os.Stat(path)
	if rootErr == nil && pathErr == nil && os.SameFile(rootInfo, pathInfo) {
		return true, true, nil
	}
	contains, err = aliasesAuthorityAncestor(root, path)
	return contains, false, err
}

func pathContains(root, path string) bool {
	rel, err := filepath.Rel(root, path)
	return err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

func aliasesAuthorityAncestor(root, path string) (bool, error) {
	rootInfo, err := os.Stat(root)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	for current := path; ; current = filepath.Dir(current) {
		info, err := os.Stat(current)
		if err == nil && os.SameFile(rootInfo, info) {
			return true, nil
		}
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return false, err
		}
		parent := filepath.Dir(current)
		if parent == current {
			return false, nil
		}
	}
}

func parseAuthorityMountPlan(options []string) (authorityMountPlan, error) {
	var plan authorityMountPlan
	for i := 0; i < len(options); i++ {
		arg := options[i]
		// Docker's pflag parser also accepts a value-taking -v after bundled boolean short flags
		// (for example -iv/host:/box). Refuse that ambiguous spelling rather than letting an
		// uninspected bind through; separating -i and -v is equivalent and unambiguous.
		if strings.HasPrefix(arg, "-") && !strings.HasPrefix(arg, "--") && !strings.HasPrefix(arg, "-v") && strings.Contains(arg[1:], "v") {
			return plan, fmt.Errorf("runtime option %q bundles -v with another short flag; write -v and its mount as separate arguments", arg)
		}
		// Docker's pflag parser accepts the short value joined to -v (for
		// example, -v/host:/box), so inspect that spelling before the generic
		// long-option handling below.
		if strings.HasPrefix(arg, "-v") && arg != "-v" && !strings.HasPrefix(arg, "--") {
			value := strings.TrimPrefix(arg, "-v")
			value = strings.TrimPrefix(value, "=")
			if err := addVolumeShorthand(&plan, value); err != nil {
				return plan, err
			}
			continue
		}
		name, value, inline := strings.Cut(arg, "=")
		readValue := func() (string, error) {
			if inline {
				return value, nil
			}
			if i+1 >= len(options) {
				return "", fmt.Errorf("%s needs a value", name)
			}
			i++
			return options[i], nil
		}
		switch name {
		case "-v", "--volume":
			value, err := readValue()
			if err != nil {
				return plan, err
			}
			if err := addVolumeShorthand(&plan, value); err != nil {
				return plan, err
			}
		case "--mount":
			value, err := readValue()
			if err != nil {
				return plan, err
			}
			if err := addLongMount(&plan, value); err != nil {
				return plan, err
			}
		case "--env-file":
			value, err := readValue()
			if err != nil {
				return plan, err
			}
			if value == "" {
				return plan, errors.New("--env-file needs a value")
			}
			plan.envFiles = append(plan.envFiles, value)
		case "--volumes-from":
			if _, err := readValue(); err != nil {
				return plan, err
			}
			plan.volumesFrom = true
		case "--volume-driver":
			if _, err := readValue(); err != nil {
				return plan, err
			}
			plan.customVolumeDriver = true
		}
	}
	return plan, nil
}

func addVolumeShorthand(plan *authorityMountPlan, value string) error {
	parts := strings.Split(value, ":")
	if len(parts) < 2 || len(parts) > 3 || parts[0] == "" {
		return errors.New("runtime volume has an ambiguous source")
	}
	writable := true
	if len(parts) == 3 {
		for _, option := range strings.Split(parts[2], ",") {
			if option == "ro" || option == "readonly" {
				writable = false
			}
		}
	}
	if looksLikePath(parts[0]) {
		if !filepath.IsAbs(parts[0]) {
			return errors.New("anchored runtime bind sources must be absolute host paths")
		}
		plan.binds = append(plan.binds, authorityBind{source: parts[0], writable: writable})
		return nil
	}
	if writable {
		plan.writableVolumes = append(plan.writableVolumes, parts[0])
	} else {
		plan.readonlyVolumes = append(plan.readonlyVolumes, parts[0])
	}
	return nil
}

func addLongMount(plan *authorityMountPlan, value string) error {
	fields, err := csv.NewReader(strings.NewReader(value)).Read()
	if err != nil {
		return errors.New("runtime mount descriptor could not be read")
	}
	kind, source := "", ""
	writable := true
	custom := false
	for _, field := range fields {
		key, fieldValue, hasValue := strings.Cut(field, "=")
		switch key {
		case "type":
			kind = fieldValue
		case "source", "src":
			source = fieldValue
		case "readonly", "ro":
			writable = !(fieldValue == "" || fieldValue == "true" || !hasValue)
		case "volume-driver", "volume-opt":
			custom = true
		}
	}
	switch kind {
	case "bind":
		if source == "" || !filepath.IsAbs(source) {
			return errors.New("anchored runtime bind sources must be absolute host paths")
		}
		plan.binds = append(plan.binds, authorityBind{source: source, writable: writable})
	case "volume":
		plan.customVolumeDriver = plan.customVolumeDriver || custom
		if source == "" { // an anonymous default volume has no pre-existing host definition
			return nil
		}
		if writable {
			plan.writableVolumes = append(plan.writableVolumes, source)
		} else {
			plan.readonlyVolumes = append(plan.readonlyVolumes, source)
		}
	case "tmpfs", "image":
	case "":
		return errors.New("anchored runtime --mount needs an explicit type")
	default:
		return fmt.Errorf("anchored runtime mount type %q cannot be inspected", kind)
	}
	return nil
}
