// Command gendocs renders the CLI reference from internal/cli (the single source of truth) into the
// committed docs, so help.go can't silently drift from them. It writes docs/cli.md (the offline
// reference) and site/llms.txt (an agent-readable plain-text manual) from cli.RenderManual — the same
// bytes `coop help --all` prints. `-check` re-renders and fails (non-zero, naming the file) if a
// committed file differs, so `make check` catches a help.go edit that wasn't regenerated. Without
// -check it writes the files. stdlib + internal/cli only.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/AndrewDryga/coop/internal/cli"
	"github.com/AndrewDryga/coop/internal/config"
)

func main() {
	check := flag.Bool("check", false, "fail if a committed doc differs from a fresh render (no writes)")
	flag.Parse()

	manual := cli.RenderManual(config.Load())
	targets := map[string]string{
		filepath.Join("docs", "cli.md"): "# coop — CLI reference\n\n" +
			"<!-- Generated by tools/gendocs from internal/cli. Do NOT edit by hand; run: go run ./tools/gendocs -->\n\n" +
			"```\n" + manual + "```\n",
		filepath.Join("site", "llms.txt"): manual,
	}

	drift := false
	for path, want := range targets {
		if *check {
			got, err := os.ReadFile(path)
			if err != nil || string(got) != want {
				fmt.Fprintf(os.Stderr, "gendocs: %s is stale — run: go run ./tools/gendocs\n", path)
				drift = true
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s\n", path)
	}
	if drift {
		os.Exit(1)
	}
}
