// Command gendocs renders the CLI reference from internal/cli (the single source of truth) into the
// committed docs, so help.go can't silently drift from them. It writes docs/cli.md (the offline
// reference), site/llms.txt (an agent-readable plain-text manual), and docs/man/coop.1 (the man page shipped
// in the release archive) from cli.RenderManual — the same bytes `coop help --all` prints. `-check`
// re-renders and fails (non-zero, naming the file) if a committed file differs, so `make check`
// catches a help.go edit that wasn't regenerated. Without -check it writes the files. stdlib +
// internal/cli only.
//
// The README's command tables are intentionally NOT generated here: they're hand-curated (links +
// prose richer than help.go's terse rows), so regenerating them would clobber that. If a generated
// command index is ever wanted, add it in its own marker-bounded block — don't overwrite the tables.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/AndrewDryga/coop/internal/cli"
	"github.com/AndrewDryga/coop/internal/config"
)

func main() {
	check := flag.Bool("check", false, "fail if a committed doc differs from a fresh render (no writes)")
	flag.Parse()

	manual := cli.RenderManual(config.Load())
	targets := map[string]string{
		filepath.Join("docs", "cli.md"): "# coop — CLI reference\n\n" +
			"<!-- Generated by tools/gendocs from internal/cli. Do NOT edit by hand; run: go run ./tools/gendocs -->\n\n" +
			"```\n" + manual + "```\n",
		filepath.Join("site", "llms.txt"):      manual,
		filepath.Join("docs", "man", "coop.1"): manPage(manual),
	}

	drift := false
	for path, want := range targets {
		if *check {
			got, err := os.ReadFile(path)
			if err != nil || string(got) != want {
				fmt.Fprintf(os.Stderr, "gendocs: %s is stale — run: go run ./tools/gendocs\n", path)
				drift = true
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s\n", path)
	}
	if drift {
		os.Exit(1)
	}
}

// manPage renders the manual as a man(1) page: a NAME line (so apropos/mandb can index it) then the
// full reference verbatim in a no-fill block — byte-identical to `coop help --all`. It stays
// deterministic (no date or version in .TH) so the -check gate holds across commits and days. roff
// needs two escapes, handled by roffEscape: a literal backslash becomes \e, and a line starting with
// . or ' would be read as a control request even inside .nf, so it's shielded with a leading \&.
func manPage(manual string) string {
	desc := strings.TrimPrefix(strings.SplitN(manual, "\n", 2)[0], "coop — ")
	var b strings.Builder
	b.WriteString(`.TH COOP 1 "" "coop" "coop Manual"` + "\n")
	b.WriteString(".SH NAME\ncoop \\- " + roffEscape(desc) + "\n")
	b.WriteString(".SH DESCRIPTION\n")
	b.WriteString("The complete command reference, identical to what \\fBcoop help \\-\\-all\\fR prints.\n")
	b.WriteString(".PP\n.nf\n")
	b.WriteString(roffEscape(manual))
	if !strings.HasSuffix(manual, "\n") {
		b.WriteString("\n")
	}
	b.WriteString(".fi\n")
	return b.String()
}

// roffEscape makes arbitrary text safe as man-page body: a literal backslash becomes \e, and any
// line that starts with a roff control character (. or ') is shielded with a zero-width \& so it
// renders as text rather than being parsed as a request. Backslashes are replaced FIRST so the \&
// shields aren't themselves mangled.
func roffEscape(s string) string {
	s = strings.ReplaceAll(s, `\`, `\e`)
	lines := strings.Split(s, "\n")
	for i, ln := range lines {
		if strings.HasPrefix(ln, ".") || strings.HasPrefix(ln, "'") {
			lines[i] = `\&` + ln
		}
	}
	return strings.Join(lines, "\n")
}
